### ISSUE TITLE
authorization issue

### ISSUE THREAD

**Issue by nerdCopter** [reznikmm/upload-bintray-action#1]
your market-place app is the only one that gets past the docker loading without error, (including `hpcsc/upload-bintray-docker-action@v1` which you seem to have collaborated.)

However i am unsuccessful with authorization.  Separately, I can cURL upload with my API-Key from my desktop, but such requires specifically a bintray-personal-account in addition to the bintray-organization-account, whereas with this github-action, the username would be the bintray organization account instead of my personal account and no other personal-account as an option.

e.g. `curl -T upload.txt -umyusername:mykey https://api.bintray.com/content/emuflight-dev/repo/package/version/upload.txt`

```
    # Upload to Bintray before .hex renames / only for tag
    - name: Upload to Bintray
      uses: reznikmm/upload-bintray-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        #username: ${{ secrets.BINTRAYUSERNAME }} # username from user profile page.
        username: emuflight-dev
        #repository: emuflight-dev/dev_hex
        repository: dev_hex
        package: ${{ steps.get_revtag.outputs.REVISION_TAG}}
        version: ${{ github.run_number }}-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_revtag.outputs.REVISION_TAG}}
        sourcePath: 'obj/*.hex'
        apiKey: ${{ secrets.BINTRAYAPIKEY }} # An API key obtained from the user profile page.
```
i tried a couple variations as you see commented out above.

```
> Run reznikmm/upload-bintray-action@v1
  with:
    username: emuflight-dev
    repository: dev_hex
    package: testBintray
    version: 556-0.3.1-testBintray
    sourcePath: obj/*.hex
    apiKey: ***
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
    GITHUBBUILDNUMBER: 556
Error: Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object]
    },
   disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://api.bintray.com//content/emuflight-dev/dev_hex/EmuFlight_0.3.1_HELIOSPRING_Build_556_6ebe54c58.hex',
    status: 401,
    statusText: 'Unauthorized',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
##[error]Upload failed
```

the variation:
```
Error: Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object]
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://api.bintray.com//content/***/emuflight-dev/dev_hex/EmuFlight_0.3.1_FOXEERF405_Build_562_0a9750d1c.hex',
    status: 404,
    statusText: 'Not Found',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
```

any clues on how to proceed? Thank you.

ref: https://github.com/emuflight/EmuFlight/actions/runs/132515911
& https://github.com/emuflight/EmuFlight/actions/runs/132553129

**Comment by reznikmm** [comment]
@nerdCopter 
I've added one more parameter - `subject`. Can you try `reznikmm/upload-bintray-action@1c9b29a` or `reznikmm/upload-bintray-action@master` action? Does it work for you?
For the command:
```
curl -T upload.txt -umyusername:mykey https://api.bintray.com/content/emuflight-dev/repo/package/version/upload.txt
```
It should be
```
    - name: Upload to Bintray
      uses: reznikmm/upload-bintray-action@master
      with:
        subject: emuflight-dev
        repository: repo
        package: package
        version: version
        sourcePath: upload.txt
        username: myusername
        apiKey: mykey
```

**Comment by nerdCopter** [comment]
failed, but unclear result 400.  possibly not your issue.
would this autocreate & publish new package/version?
i notice no `package` listed in response URL, and a double `//` after .com
edit: cURL version requires pre-made package/version (hope to avoid such)

```
    # Upload to Bintray before .hex renames / only for tag
    - name: Upload to Bintray
      uses: reznikmm/upload-bintray-action@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        subject: emuflight-dev
        repository: dev_hex
        package: ${{ steps.get_revtag.outputs.REVISION_TAG}}
        version: ${{ github.run_number }}-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_revtag.outputs.REVISION_TAG}}
        sourcePath: obj/*.hex
        username: ${{ secrets.BINTRAYUSERNAME }} # username from user profile page.
        apiKey: ${{ secrets.BINTRAYAPIKEY }} # An API key obtained from the user profile page.
```

```
Run reznikmm/upload-bintray-action@master
  with:
    subject: emuflight-dev
    repository: dev_hex
    package: testBintray
    version: 580-0.3.1-testBintray
    sourcePath: obj/*.hex
    username: ***
    apiKey: ***
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
    GITHUBBUILDNUMBER: 580
```

```
Error: Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object]
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://api.bintray.com//content/emuflight-dev/dev_hex/EmuFlight_0.3.1_STRIXF10_Build_580_68677994a.hex',
    status: 400,
    statusText: 'Bad Request',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
##[error]Upload failed
```

https://github.com/emuflight/EmuFlight/actions/runs/133648102
https://github.com/emuflight/EmuFlight/actions/runs/133642833
